{% set name = "django-viewflow" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-viewflow-{{ version }}.tar.gz
  sha256: edb0d9bf20b406fff781eea91cd3d250cde3b3ff956ce6451ceeabab3bbc8f94

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.7,<3.11
    - django >=2.2
    - django-filter >=1.0
    - django-jsonstore
    - django-annoying
    - six

test:
  imports:
    - viewflow
  commands:
    - pip check
    - python -c "import django; from django.conf import settings; settings.configure(INSTALLED_APPS=['viewflow']); django.setup(); import viewflow; import viewflow.flow; import viewflow.flow.views; import viewflow.management; import viewflow.migrations; import viewflow.nodes; import viewflow.templatetags; import viewflow.frontend; import viewflow.frontend.templatetags"
  requires:
    - pip

about:
  home: http://viewflow.io/
  license: AGPL-3.0
  license_family: GPL3
  license_file: LICENSE
  summary: 'Reusable workflow library for Django'
  description: |
    Viewflow takes the best parts from two worlds. It is based on BPMN - 
    business process modeling and notation standard - and plays well with the 
    django web development toolchain. BPMN provides a standard notation, 
    readily understandable by all business stakeholders. Viewflow bridges 
    the gap between a picture and an executable, ready to use web application.
  doc_url: http://docs.viewflow.io/
  dev_url: https://github.com/viewflow/viewflow/

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
 
