{% set name = "django-viewflow" %}
{% set version = "1.5.6" %}
{% set sha256 = "51d4067416ab5b5002fff4d8deac4c3757e1b5ad85e0112bebb912d50a60c873" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - django >=1.8
    - django-filter >=1.0

test:
  commands:
    - python -c "import django; from django.conf import settings; settings.configure(INSTALLED_APPS=['viewflow']); django.setup(); import viewflow; import viewflow.flow; import viewflow.flow.views; import viewflow.management; import viewflow.migrations; import viewflow.nodes; import viewflow.templatetags; import viewflow.frontend; import viewflow.frontend.templatetags"

about:
  home: http://viewflow.io/
  license: AGPL-3.0
  license_family: GPL3
  license_file: LICENSE
  summary: 'Reusable workflow library for Django'
  description: |
    Viewflow takes the best parts from two worlds. It is based on BPMN - 
    business process modeling and notation standard - and plays well with the 
    django web development toolchain. BPMN provides a standard notation, 
    readily understandable by all business stakeholders. Viewflow bridges 
    the gap between a picture and an executable, ready to use web application.
  doc_url: http://docs.viewflow.io/
  dev_url: https://github.com/viewflow/viewflow/

extra:
  recipe-maintainers:
    - cshaley
