travis:
  secure:
    BINSTAR_TOKEN: fS0R4c3hG4LMVtK4QIFPqHPS5F+0H+BrdKXXUicyLG/EOwgHaGb0PfFtxV8oO+X9/kEjqPe+1pr/XEGU2w3Z6d8OpRoq6Isop1hbzqcX3zX4DQjuKmnM0vAR9omQJP4U6ez0ELsIGpO0PWgwQACRMWrnZ0tvJXBDFtfNr/QPSnzA5aNg62X4cd7imDCk7fRxFV+h9peueLNkX5mhZGybZNENFYdNA7GLlZmDSyo+vibM1cPEO07+s5513bQPe5azy+Sn1uzScZdK+riCitgINm1RYFVExiBioYHZs4sDLQ65Gy8rhV0J3VC/kMKd8aLDS9kq/Fm3yK9nx+fQ2xRPdKIHBCFF1LBm2ZR0EBnJ5TtfEw/ZyGDeDmVVjL8dR4n7dni4tbM5rqPqqUaBs/VRQK+I1Mu54tZmGhS7Kjovw0nVjgmOLweXgMklEJLnqowwIRXf3Bbmof95fuvqCElQxmx0Q84AEzQq11S+x3zCJg9Ifb9Cl1Qsibc68wlyqHSC5aYYcSWe09pZDxOdpeXCs+iHqy/9/pU/5xAzV3iLdPEWwufvMl8BfbrfgcR16S4NktUNs+tEwMFmO+S1G6iOM55q74zkYD1zyeM1nGtFC+/8lZ1RtYVMNJ9e0SX5MIHpdSQDsmZ+uhx2X3REbD/tPiQ1+j76BTEs15+rTeRVHnE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
