travis:
  secure:
    BINSTAR_TOKEN: ULvkm8Mb5FBnOF+ZiY92UdVVaBFbzjZ/cfkPsmCg6FRKXAiT5KyosBUxguHiR2O974Ej3hLtosOhA4F5JH/t5vClx5PhS1YRBB7POnHEGZpqCTY5mQI9O2I0Qzz0R9oPURe4dEPaTIJ60B+BtRvHu1zn3ZdbTiohrrjFK73uTmumTUnGAOE7D8tvQoHFwUFxQ+UUiYC0X/ABhUDOEPC0x3/PBbHmZ2KU/+xkm+/H/RXSzHyV52bQd3/r3OYjprM/7emlRxKISxfUdNxsIllh9qqDtlPGU8Q95TUfGdso5Ii1lq7rH+GWCS6a/6h4nOG3Wx83cA2gYhpwSR83AkZfdjNLHg7PtEORNlyu6edYeAVa0825SlHVAT3NmmVSHLkUbY03DScpBRG6k/y5dPEOKz/M+ymA7BHzlmu8WY0tv1TbCXVelYcsPEhdwC3PxNvSWovEapl0Tfz6et4iorIKS+MxNM8vBRkt9gJOg+K8AJ1w6zmCwHQZyRiMa5k6FjEs2DZ3oivFtez+URn7P+k/nGcvNEUzd1WoCTQK//E3uFERgav5t7kSQIdi0GZrm8Nm73gzGpR4TGAIhF6ZXETzoGA2H/MsRG6ZA4ubDkM4cXrxrcUOBGP6+48EDFon7Cbdjipox9uydj+CfoJPQVsxHSUv2ZQZ0D3aCXd8h3/P26w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
